fixed bug
line 165 caused an error when you used the "-l" parameter to label the samples. 
TypeError: list indices must be integers, not list

Therefore, I changed the line so that it now works!